---
# Manage Nginx web servers

- name: 'Install Nginx web server'
  ansible.builtin.include_tasks:
    file: 'install.yaml'
  tags:
    - nginx_install

- name: 'Manage Nginx web server'
  ansible.builtin.include_tasks:
    file: 'manage.yaml'
  tags:
    - nginx_start
    - nginx_stop
    - nginx_restart
    - nginx_status
