---
# Setup baseline Linux configurations based on server type
# File: baseline-linux.yaml
# Usage: ansible-playbook -i inventory --limit plvm-okdlb01 --tags baseline-linux baseline-linux.yaml

- hosts: all
  become: yes
  become_user: ansible
  roles:
    - baseline-linux
