---
# Setup baseline Linux configurations
# File: baseline-linux.yaml
# Usage: ansible-playbook -i inventory --limit plvm-okdlb01 --tags baseline-linux baseline-linux.yaml

- hosts: all
  become: yes
  roles:
    - baseline-linux
