---
# Setup baseline Linux configurations
# File: set-baseline-server.yaml
#
# Tags:
# - baseline - Apply server/user baselines
# - new_vm   - Build a new VM (apply server/user baselines, update packages)
# - update   - Update packages
# - upgrade  - Update packages and upgrade (for Fedora only)
#
# Vars:
# - vm_hostname - Host name for new VM

- hosts: all
  become: yes
  roles:
    - baseline-linux
