---
# Setup baseline Linux configurations
# File: new-vm.yaml
#
# Tags:
# - new_vm   - Build a new VM (clone template, start VM, apply server/user baselines, update packages)
#
# Vars:
# - proxmox_template_id - Template ID to clone for new VM
# - vm_newid            - New VM ID
# - vm_hostname         - Host name for new VM

- hosts: all
  become: yes
  roles:
    - proxmox
    - baseline-linux
