---
# Update and/or Upgrade Linux or Windows
# File: update.yaml

- hosts: all
  become: yes
  roles:
    role: update

  handlers:
  - name: 'Reboot after installing updates'
    ansible.builtin.reboot:
      msg: 'Rebooting after installing updates.'
    listen: 'reboot'
