---
# Update and/or Upgrade Linux
# File: update-linux.yaml
#
# Tags:
# - update   - Update packages
# - upgrade  - Update packages and upgrade (for Fedora only)

- hosts: all
  become: yes
  roles:
    - update-linux

  handlers:
  - name: 'Reboot after installing updates'
    ansible.builtin.reboot:
      msg: 'Rebooting after installing updates.'
    listen: 'reboot'
    tags: [ 'update', 'upgrade' ]
