---
# Update and/or Upgrade Linux
# File: update-linux.yaml

- hosts: all
  become: yes
  roles:
    - update-linux

  handlers:
  - name: 'Reboot after installing updates'
    ansible.builtin.reboot:
      msg: 'Rebooting after installing updates.'
    listen: 'reboot'
