---
# Stop and/or start a Proxmox VM
# File: vm-stop-start.yaml

- hosts: localhost
  pre_tasks:
    - name: 'Fail if required variables are undefined'
      ansible.builtin.fail:
        msg: 'The variable ''{{ required_var }}'' is required.'
      when: required_var not in hostvars[inventory_hostname]
      loop:
        - vm_hostname
      loop_control:
        loop_var: required_var

    - name: 'Fail if vm_state variable is invalid'
      ansible.builtin.fail:
        msg: 'Valid ''vm_state'' values: status, started, stopped, restarted, paused, or hibernated.'
      when: vm_state not in [ 'status', 'started', 'stopped', 'restarted', 'paused', 'hibernated' ]

  roles:
    - role: proxmox-qemu-stop-start
