---
# Stop and/or start a Proxmox VM
# File: vm-stop-start.yaml

- hosts: localhost
  pre_tasks:
    - name: 'Fail if required variables are not defined'
      ansible.builtin.fail:
        msg: 'The variable ''{{ required_var }}'' is required.'
      when: required_var not in hostvars[inventory_hostname]
      loop:
        - vm_hostname
      loop_control:
        loop_var: required_var

    - name: 'Print supported vm_action variable values if one is not supplied'
      ansible.builtin.debug:
        msg: 'Valid variable vm_action values: started, stopped, restarted, paused, hibernated.'
      when: vm_action not in [ 'started', 'stopped', 'restarted', 'paused', 'hibernated' ]

  roles:
    - role: proxmox-qemu-stop-start
