---
# Stop and/or start a Proxmox VM
# File: vm-stop-start.yaml

- hosts: localhost
  pre_tasks:
    - name: 'Fail if required variables are undefined'
      ansible.builtin.fail:
        msg: 'The variable ''{{ required_var }}'' is required.'
      when: required_var not in hostvars[inventory_hostname]
      loop:
        - vm_hostname
      loop_control:
        loop_var: required_var

    - name: 'Warn if vm_action variable is undefined'
      ansible.builtin.debug:
        msg: 'Valid variable ''vm_action'' values: started, stopped, restarted, paused, or hibernated.  If none provided, status will be used.'
        verbosity: 1
      when: vm_action not in [ 'started', 'stopped', 'restarted', 'paused', 'hibernated' ]

  roles:
    - role: proxmox-qemu-stop-start
