---
# Manage Proxmox and build VMs using the Proxmox API
# File: roles/proxmox/tasks/main.yaml

- name: 'Include Proxmox cluster information tasks'
  ansible.builtin.include_tasks:
    file: 'pve-info.yaml'
  tags: [ 'pve_version' ]

- name: 'Include clone template tasks'
  ansible.builtin.include_tasks:
    file: 'vm-clone.yaml'
  tags: [ 'clone' ]

- name: 'Include stop and/or start VM tasks'
  ansible.builtin.include_tasks:
    file: 'vm-stop-start.yaml'
  tags: [ 'stop', 'start', 'clone' ]
