---
# Manage Proxmox and build VMs using the Proxmox API
# File: roles/proxmox/tasks/main.yaml

- name: Include cluster information tasks
  ansible.builtin.include_tasks:
    file: info.yaml
  tags: [ pve_version ]

- name: Include VM management tasks
  ansible.builtin.include_tasks:
    file: vm.yaml
  tags: [ new_vm, stop_vm, start_vm ]
