---
# Update packages for Debian OS family
# File: roles/update/tasks/update-debian.yaml

- name: 'Check for updates using apt'
  ansible.builtin.command:
    cmd: 'apt list --upgradeable'
  register: packages_avail
  failed_when: packages_avail.rc not in [ 0, 100 ]

- name: 'Packages to update'
  ansible.builtin.debug:
    var: packages_avail.stdout_lines
    verbosity: 0

- name: 'Install updates using apt'
  ansible.builtin.apt:
    name: "*"
    state: 'latest'
    update_cache: true
  notify: 'reboot'
  register: packages_updated

- name: 'Packages updated'
  ansible.builtin.debug:
    var: packages_updated.results
