---
# Setup SSH keys

# ssh-keygen -q -N "" -C "plvm-k8s01 ansible" -f ~/.ssh/plvm-k8s01
# ll ~/.ssh/
# ssh-copy-id -i ~/.ssh/plvm-k8s01.pub ansible@192.168.7.241


- name: 'Run ssh-keygen'
  ansible.builtin.shell: 'ssh-keygen -q -N "" -C "Ansible SSH key" -f ~/.ssh/id_rsa'
  args:
    creates: '~/.ssh/id_rsa'
  tags: [ ssh_keys ]

- name: 'Copy public key to Ansible node'
  ansible.builtin.fetch:
    src: '~/.ssh/id_rsa.pub'
    dest: 'buffer/{{ansible_hostname}}-id_rsa.pub'
    flat: true
  tags: [ ssh_keys ]

- name: 'Add authorized key'
  ansible.posix.authorized_key:
    user: 'ansible'
    state: 'present'
    key: '{{ lookup("file", "buffer/{{ansible_hostname}}-id_rsa.pub") }}'
  tags: [ ssh_keys ]
