---
# Update and/or Upgrade Linux
# File: roles/update-linux/tasks/main.yaml

- name: 'Include update tasks for {{ ansible_os_family }} OS family'
  ansible.builtin.include_tasks:
    file: 'update-{{ ansible_os_family | lower }}.yaml'

- name: 'Include upgrade tasks for Fedora distribution'
  ansible.builtin.include_tasks:
    file: 'upgrade-fedora.yaml'
  when:
    - ansible_distribution == 'Fedora'
    - new_version != ''
