---
# Upgrade Fedora distribution
# File: roles/update-linux/tasks/upgrade-fedora.yaml

- name: 'Verify new_version is defined'
  ansible.builtin.assert:
    that: new_version != ''
    fail_msg: 'The new_version variable needs to be set.'
    success_msg: 'Upgrading to {{ new_version }}.'
    quiet: true
  tags: [ 'upgrade' ]

- name: 'Download Fedora upgrade packages'
  ansible.builtin.expect:
    command: 'dnf system-upgrade download --releasever={{ new_version }}'
    responses:
      'Before you continue': 'y'
      'Is this ok': 'y'
    timeout: 300
  register: packages_download
  tags: [ 'upgrade' ]

- name: 'Start the upgrade'
  ansible.builtin.command:
    cmd: 'dnf system-upgrade reboot'
  tags: [ 'upgrade' ]
