---
# Setup baseline Linux configurations
# File: roles/baseline-linux/tasks/main.yaml

- name: Include baseline server configuration tasks
  ansible.builtin.include_tasks:
    file: server.yaml
  tags: [ new_vm, baseline ]

- name: Include baseline user configuration tasks
  ansible.builtin.include_tasks:
    file: user.yaml
  tags: [ new_vm, baseline ]

- name: Include package update tasks
  ansible.builtin.include_tasks:
    file: update.yaml
  tags: [ new_vm, update, upgrade ]

- name: Include Fedora upgrade tasks
  ansible.builtin.include_tasks:
    file: upgrade.yaml
  tags: [ upgrade ]
