---
# Setup baseline Linux configurations
# File: roles/baseline-linux/tasks/user.yaml

- name: Delete template user
  ansible.builtin.user:
    name: template
    remove: true
    state: absent
  tags: [ new_vm, baseline ]
